### ISSUE TITLE
What about multiple consumers?

### ISSUE THREAD

**Issue by tnn24** [pact-foundation/pact-specification#33]
More specifically, consumers using the same functionality defining their own API. What happens if the consumers have different pact specs for the same provider, on the same functionality?

Also, wouldn't having multiple consumers using different parts of one producers cause the producer's API doc to be fragmented, hard to review?

Sorry, I'm new to this, if these issues have been addressed.

**Comment by bethesque** [comment]
Hi @tnn24. Once the first pact has been created, the next consumers need to ensure they comply with the original pact - they may use more or less, but the parts that overlap need to be the same. It would be helpful to give the next consumer team a copy of the first pact. 

If one or more consumers wants a change to the provider, and the provider team agrees to this, then the pacts will help you identify which consumers are using a certain field. You can then add the new field along side the old field, ensure all the consumers are using the new field, then remove the old field. Pacts will help you do this, as once all the consumers have switched to the new field, you will be able to remove the old field from the provider, and all the pacts should still pass. If they fail, you know that some consumer out there is still using the old field.

Remember that pacts are solving a technological problem - they cannot solve people problems (eg. when 2 teams want a different thing), but they can help you identify them.

> Also, wouldn't having multiple consumers using different parts of one producers cause the producer's API doc to be fragmented, hard to review?

Do not think of the pact as documenting the provider's API - they are documenting the contract between a certain consumer and provider. This is more useful, as it tells you what fields the consumer actually cares about, and what the impact of changes will be.

**Comment by tnn24** [comment]
Thanks for you reply!

In the case of multiple consumers, new consumers have to dig through existing pact files, which most likely contain duplicated endpoints. Wouldn't it easier to just have the producer defining the API in, say, a Swagger specs, and have all the consumers abide to it? The consumers just have to test against that specs. When a change needs to happen, everybody needs to talk to each other, but that's what being done anyway.

**Comment by bethesque** [comment]
@mefellows can you tell us about the swagger/pact thing that atlassian did?

**Comment by uglyog** [comment]
Here is the bitbucket repo: https://bitbucket.org/atlassian/swagger-request-validator

**Comment by mefellows** [comment]
This was the more recent one:
https://bitbucket.org/atlassian/swagger-mock-validator

**Comment by mefellows** [comment]
@tnn24 our [Pact Broker](https://github.com/bethesque/pact_broker) provides a visualisation that helps with this, including live documentation that matches your actual code.

As @bethesque mentioned, one challenge with using Swagger in my experience is that you can't always guarantee that your code stays in sync with it.

This is probably the most common scenario we see - both Swagger (for docs) and Pact (for contract verification).

**Comment by 121371** [comment]
What I understood is in case of multiple consumers, we will have to take the first published pact and add more interactions which next consumer wants to do. But while publishing the next pact what will be the consumer name because we have multiple consumers associated with that pact.

**Comment by 121371** [comment]
Hey Matt, Looks like I am clear now with sentence you mentioned. Thanks !!

**Comment by YOU54F** [comment]
Think everyone sounds happy here, so going to close.

Thanks @121371 & @tnn24. 

Feel free to reach out on https://slack.pact.io if you want to continue the discussion
