### ISSUE TITLE
Add consumer contact details to pact file

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-specification#34]
Originally suggested here: https://github.com/realestate-com-au/pact/issues/116

Perhaps:

``` ruby
Pact.consumer "Foo consumer" do

  supported_by "Foo Team on Level 3", with_email_address: "team@foo.com"

  has_pact_with "Foo provider" do
  end
end

```

``` json
"consumer": {
    "name": "Foo consumer",
    "supportName": "Foo Team on Level 3",
    "supportEmailAddress": "team@foo.com"
  },
```

**Comment by uglyog** [comment]
While this is a useful feature, I'm unsure if it should be stored in the Pact file. This raises some questions about behavior when the values change.

**Comment by bethesque** [comment]
I think this should be a Broker feature, not a pact feature.

**Comment by bethesque** [comment]
2020 Beth disagrees with 2017 Beth.
