### ISSUE TITLE
Add metadata to providerState and support for multiple states

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-specification#40]
@uglyog I can't remember if this happened in v3+ or not. Like:

```json

providerStates: [
{"name": "a thing exists", "metadata": {"id": 1}},
{"name": "and another thing exists", "metadata": {"name": "foo"}}
]
```

**Comment by uglyog** [comment]
https://github.com/pact-foundation/pact-specification/tree/version-3#allow-multiple-provider-states-with-parameters

Your welcome!

**Comment by bethesque** [comment]
Awesome! That's something I want to prioritise in the ruby impl.
