### ISSUE TITLE
Review of pact-json-schema v2

### ISSUE THREAD

**Issue by BenSayers** [pact-foundation/pact-specification#43]
I added the schema for pact v2 to the pact-json-schema codebase. Do you mind doing a review for correctness?

https://bitbucket.org/atlassian/pact-json-schema/src/8c17153c5658b9e2dff8404c7cc3751fe3e9ebdd/schemas/v2/schema.json?at=master&fileviewer=file-view-default

The differences between v2 and v1 schemas are the addition of matching rules to request and responses as well as the removal of the legacy provider_state (now providerState) property on the interaction object.

**Comment by bethesque** [comment]
@uglyog is match=equality a thing you've added in a later version, or in jvm? I've not used it before.

https://bitbucket.org/atlassian/pact-json-schema/src/8c17153c5658b9e2dff8404c7cc3751fe3e9ebdd/schemas/v2/schema.json?at=master&fileviewer=file-view-default#schema.json-48

**Comment by bethesque** [comment]
@BenSayers if you want to use the official terminology (which I'm regretting now!), it's "pacticipant".

**Comment by bethesque** [comment]
There is also the metadata which I believe we decided should look like
```json
metadata: {
  pactSpecification: {
    version: "1.2.3"
  }
}
```

but I think the pact-jvm still uses pact-specification.

**Comment by BenSayers** [comment]
@bethesque I got the equality matcher from the docs here:
https://github.com/pact-foundation/pact-specification/tree/version-2#supported-matchers

I'm hunting for a test case that uses it but haven't found one yet...

**Comment by uglyog** [comment]
The equality matcher is used to reset matching when like matchers cascade in the JVM version. But it is the default matching when no matcher is specified, so not supporting it has no effect.

**Comment by BenSayers** [comment]
The equality matcher is mentioned as a new feature in the v3 docs. So I propose we remove it from the v2 docs in this project and I'll remove it from the v2 json schema as well.

https://github.com/pact-foundation/pact-specification/tree/version-3#add-an-equality-matcher

**Comment by BenSayers** [comment]
Here are all the variations of metadata I could find amongst our pact files:
```
    "metadata": {
        "pactSpecificationVersion": "2.0.0"
    },
```

```
    "metadata": {
        "pact-specification": {
            "version": "2.0.0"
        },
        "pact-jvm": {
            "version": "3.2.6"
        }
    },
```

```
    "metadata": {
        "pactSpecification": {
            "version": "2.0.0"
        }
    },
```

And some of our pact files don't have a metadata property at all. So I could add a definition of this to the schema but it would have to be an optional property defined as a "oneOf" operation with the schemas for the 3 variations. Let me know if you think that's a useful thing to have in the schema and I'll add it.

**Comment by bethesque** [comment]
Please add the metadata, and set it to the last example. It's what we should all move to. If it's going to fail in annoying ways, just make it optional.

**Comment by BenSayers** [comment]
I have mixed feelings about only adding the 1 variation. I like that it sets a single standard to move toward, but arguably that is the job of future versions of the specification.

Including all 3 variations we would be documenting what you will actually find if you are looking at the metadata property of v2 pact files. For example if I wanted to write code to read the pact specification version of every pact file in our broker I would have to handle the fact these variations exist.

Thoughts?

**Comment by bethesque** [comment]
You've convinced me. Put all 3 in.

**Comment by uglyog** [comment]
I have no idea how the JVM version ended up with hyphenated keys, that is so un-JVM to do that :-D

**Comment by BenSayers** [comment]
Is this a valid pact file?
```
{
    "consumer": {
        "name": "A consumer"
    },
    "interactions": [],
    "metadata": {},
    "provider": {
        "name": "A provider"
    }
}
```
I'm trying to decide how strict I should be about the metadata definition. Should we require that if you have a metadata property defined it must contain the version number in one of the three variations?

**Comment by uglyog** [comment]
The most basic pact file is:

```json
{
    "consumer": {
        "name": "A consumer"
    },
    "interactions": [],
    "provider": {
        "name": "A provider"
    }
}
```

The metadata should be optional, and it should allow any key-value pairs.

**Comment by BenSayers** [comment]
I agree with all of that, but that doesn't answer my question.

**Comment by uglyog** [comment]
Yes it is

**Comment by BenSayers** [comment]
And just for fun is this a valid pact file?
```
{
    "consumer": {
        "name": "A consumer"
    },
    "interactions": [],
    "metadata": {
        "pactSpecificationVersion": "2.0.0",
        "pact-specification": {
            "version": "2.0.0"
        },
        "pactSpecification": {
            "version": "2.0.0"
        }
    },
    "provider": {
        "name": "A provider"
    }
}
```

**Comment by uglyog** [comment]
Yes, it would be

**Comment by BenSayers** [comment]
I released a new version of the schema incorporating all your feedback, thanks for the help @bethesque and @uglyog!

https://bitbucket.org/atlassian/pact-json-schema/src/8d0b9d2f38fe517dfbce0e5d0b8755eaefaacb5b/schemas/v2/schema.json?at=master&fileviewer=file-view-default

**Comment by bethesque** [comment]
We should probably stick it in the pact specification repo somewhere.

**Comment by BenSayers** [comment]
I’m open to it but keep in mind it has a hundred or so tests and a release process that go with it.

**Comment by bethesque** [comment]
Let's put a link to it then. Is there a "home page" for it, or should we just link to the file?

**Comment by BenSayers** [comment]
Yep, the home page is here:
https://bitbucket.org/atlassian/pact-json-schema

**Comment by bethesque** [comment]
I've added it here: https://github.com/pact-foundation/pact-specification/blob/master/README.md#index

**Comment by bethesque** [comment]
Thanks for your work on this @BenSayers

**Comment by BenSayers** [comment]
No worries. 

Fun side note: I've been playing around with generating Pact type definitions off this schema as a way of keeping tooling written in strongly typed languages consistent when it comes to working with Pact files. The only part of the schema that isn't very type system friendly is MatchingRules because I used pattern properties.

Heres a typescript example
```typescript
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Interactions = Interaction[];

/**
 * Schema for a Pact file
 */
export interface Pact {
  consumer: Pacticipant;
  interactions: Interactions;
  metadata?: Metadata;
  provider: Pacticipant;
  [k: string]: any;
}
export interface Pacticipant {
  name: string;
  [k: string]: any;
}
export interface Interaction {
  description: string;
  providerState?: string;
  request: Request;
  response: Response;
}
export interface Request {
  body?: any;
  headers?: Headers;
  matchingRules?: MatchingRules;
  method: ("connect" | "CONNECT" | "delete" | "DELETE" | "get" | "GET" | "head" | "HEAD" | "options" | "OPTIONS" | "post" | "POST" | "put" | "PUT" | "trace" | "TRACE");
  path: string;
  query?: string;
}
export interface Headers {
  [k: string]: string;
}
export interface MatchingRules {

}
export interface Response {
  body?: any;
  headers?: Headers;
  matchingRules?: MatchingRules;
  status: number;
}
export interface Metadata {
  pactSpecification?: {
    version: string;
  };
  pactSpecificationVersion?: string;
  "pact-specification"?: {
    version: string;
  };
  [k: string]: any;
}
```

If patternProperties is switched to additionalProperties the MatchingRules comes out like this:
```typescript
export interface MatchingRules {
  [k: string]: ({
    match: "type";
    max?: number;
    min?: number;
  } | {
    match: "regex";
    regex: string;
  });
}
```

I'll see how other languages generators handle that OR in the MatchingRules definition and maybe throw these definitions into swagger-mock-validator and see what happens.
