### ISSUE TITLE
Matcher for dynamic Object keys

### ISSUE THREAD

**Issue by Mende** [pact-foundation/pact-specification#47]
## Pact Matcher for objects with dynamic keys

My use case is pretty specific but i feel like it might be common.
I have an systemMessage object that has a very consistent schema that i defined like this
```
export const systemMessage = {
  id: like(123456),
  message: like('some text here'),
  priority: term({
    matcher: 'LOW|MEDIUM|HIGH|CRITICAL',
    generate: 'HIGH'
  }),
  destination: term({
    matcher: 'EVERYWHERE|SOMEWHERE|ELSEWHERE',
    generate: 'EVERYWHERE'
  })
};
```
I return a very high volume of these objects and to simplify my render process I use a hash where each message is keyed by it's ID.

```
const systemMessages = {
    123456:  MessageWithID123456
    ....
}
```
Since the objects contained in the hash are of a specific type I would like a function akin to `eachLike` for objects that simply validates that the values in the object conform to the pattern above and ignores the keys.

```
{
    systemMessages: objectLike({
      id: like(123456),
      message: like('some text here'),
      priority: term({
        matcher: 'LOW|MEDIUM|HIGH|CRITICAL',
        generate: 'HIGH'
      }),
      destination: term({
        matcher: 'EVERYWHERE|CMS',
        generate: 'EVERYWHERE'
      })
    })
}
```

I'm including a link to the react-immutable-proptypes project. They have a function called `ImmutablePropTypes.mapOf()` which does what I described. 
https://github.com/HurricaneJames/react-immutable-proptypes#api

**Comment by mefellows** [comment]
Thanks for posting this detailed request @mende.

I actually asked a few people at my place of work when this came up on the forums, and unanimously this was seen as unusual to be exposed as an API. So I'm skeptical of it being a common case.

This will take some serious thought as it is pretty core to any matching logic, although you could see how it might be implemented from a users perspective.

**Comment by uglyog** [comment]
Here is an example of a test that shows this behaviour in Pact-JVM: https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/WildcardKeysTest.java

**Comment by mefellows** [comment]
I stand corrected

**Comment by uglyog** [comment]
I propose we add a `ignoreKeys` flag to the matcher defined on the map. The current implementation in Pact-JVM is a work around and is causing other issues. I'll add this to the V4 spec.

**Comment by uglyog** [comment]
After some thought, I've decided a `matchValues` matcher defined on the map would be better. See https://github.com/pact-foundation/pact-specification/blob/version-4/README.md#ignoring-the-keys-in-a-map

**Comment by uglyog** [comment]
@joelgithub hopefully it will

**Comment by mefellows** [comment]
Just because a map is a ubiquitous concept doesn't mean it should be dumped into an API design.

APIs should be _designed_, not simply a reflection of internal data structures.

Nevertheless I'm happily convinced there are enough cases in the wild to support dynamic keys and this feature.

**Comment by quincy** [comment]
@mefellows, thank you for your feedback.  I agree that APIs should be designed.  However, many of us are working on legacy projects which were created prior to Pact.  We don't necessarily have the luxury of redesigning the API at this time but we'd still like to get contracts in place.

Let's say I was redesigning my API though.  It is the job of this particular provider service to transmit domain objects to its consumers.  These domain objects are schedules of values keyed by date.  I can imagine transforming the data from something like the following:

```
[
  {
      "accountId" : 1,
      "permissions" : [
         {
            "schedule" : {
               "01/01/2018" : false,
               "01/01/1900" : true
            },
            "permissionId" : 3
         }
      ]
   }
]
```
to something like this instead:
```
[
  {
      "accountId" : 1,
      "permissions" : [
         {
            "schedule" : [
              { "01/01/2018" : false },
              { "01/01/1900" : true }
            ],
            "permissionId" : 3
         }
      ]
   }
]
```

That would make the API work with Pact as it is today.  But I fail to see how this is fundamentally a better designed API.  Perhaps you had something else in mind and I simply can't see it at the moment.  Can you offer guidance on how something like this could be improved?  Do you have some literature you could refer me to?

I am not trying to be argumentative, but I would like to understand your comment and make improvements in the work I do in the future.

**Comment by mefellows** [comment]
Totally agree with you on the retrofitting use case, which is another strong reason to support this. 

Whether I agree with it or not doesn't matter, the fact that it is common in the real world is a good enough reason to support it.

FWIW I would have each item within `schedule` mapped to something more like the following:

```json
[
  {
      "accountId" : 1,
      "permissions" : [
         {
            "schedule" : [
                { 
                    "date": "01/01/2018",
                    "enabled": true 
                },
                { 
                    "date": "01/01/1900",
                    "enabled": false 
                },
            ],
            "permissionId" : 3
         }
      ]
   }
]
```

Having each schedule as a domain object keyed by well-defined names allows greater flexibility in the model should you choose to expand, and is more easily modelled by today's tooling (albeit OAS will be able to sort-of support this down the track: https://github.com/OAI/OpenAPI-Specification/issues/1505)

**Comment by quincy** [comment]
Thanks for sharing your opinion @mefellows.  I appreciate the insight.

**Comment by tcanavan** [comment]
Will this be implemented in 4.0.0?

**Comment by uglyog** [comment]
Not necessarily. The new matcher is added behaviour, and doesn't change the structure of the pact file.

**Comment by uglyog** [comment]
Released values matcher with Pact-JVM and Pact-Rust
