### ISSUE TITLE
create Pact mannually

### ISSUE THREAD

**Issue by ashishsinha1503** [pact-foundation/pact-specification#65]
HI , 

Is there any way to create the pact file manually (instead of creating using Test-case)  and use the same in Consumer as well as Provider ?

Thanks in advance !!!

**Comment by mefellows** [comment]
Why would you want to do this? That would mean you didn't test the consumer?

**Comment by bethesque** [comment]
Please see https://docs.pact.io/faq#can-i-generate-my-pact-file-from-something-like-swagger
