### ISSUE TITLE
Support for gRPC contract testing

### ISSUE THREAD

**Issue by krzysztofreczek** [pact-foundation/pact-specification#69]
Are there any plans for support of gRPC contract testing? 
Maybe it is already there, or there are some well-known practices on how to use pact in such a scenario?

**Comment by mefellows** [comment]
Yes there are plans, but not yet supported. See https://pact.canny.io/feature-requests/p/support-grpc and also https://github.com/pact-foundation/pact-specification/issues/62

**Comment by krzysztofreczek** [comment]
@mefellows, thanks for the quick response. Are you able to provide any rough estimation when this feature is available? I understand you are open for contributions, aren't you?

**Comment by mefellows** [comment]
I'd say in the next 3 months we'll have at least a workable beta in a popular languages (e.g. JS or Pact Go, because they are the two I maintain). Did you want to join us at slack.pact.io in the #protobufs channel, and we can discuss there? We probably have enough critical mass now we could form a working group and a plan?

**Comment by krzysztofreczek** [comment]
@mefellows, would be great! At the moment I am in a few other short term projects and would be difficult to get into your right now. Let me get back to you in a month or two and check if I can help then

**Comment by mcopjan** [comment]
Any update on this please?

**Comment by mefellows** [comment]
Please follow the https://pact.canny.io/feature-requests/p/support-grpc issue. 
Follow #83 also as it will be a pre-requisite.

![Screen Shot 2021-02-22 at 11 20 06 am](https://user-images.githubusercontent.com/53900/108643726-ec027a80-74ff-11eb-8a47-8a98ef652d39.png)

**Comment by YOU54F** [comment]
This is complete via plugins

https://github.com/pactflow/pact-protobuf-plugin
