### ISSUE TITLE
Using Matchers.ISO8601_DATETIME_WITH_MILLIS_FORMAT doesn't work as expected.

### ISSUE THREAD

**Issue by ravi-mijar-au** [pact-foundation/pact-specification#78]
In a pact-node consumer test, I have - 
```
describe('edit a policy', () => {
    const REQUEST_BODY = {
      name: 'account-holder',
      version: '2020-07-10T01:22:09.488Z',
    };
    const RESPONSE_BODY = {
      name: Matchers.like('account-holder'),
      version: Matchers.ISO8601_DATETIME_WITH_MILLIS_FORMAT,
      additionalAttributes: Matchers.like({}),
    };
    beforeEach(() =>
      provider.addInteraction({
        state: 'policy account-holder already exist',
        uponReceiving: 'edit a policy with body ',
        withRequest: {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
          },
          path: '/policies/account-holder/versions/2020-07-10T01:22:09.488Z',
          body: REQUEST_BODY,
        },
        willRespondWith: {
          status: 200,
          headers: {
            'Content-Type': 'application/json; charset=utf-8',
          },
          body: RESPONSE_BODY,
        },
      })
    );
    it('returns success', () =>
      client.updatePolicyByNameAndVersion(REQUEST_BODY).then((policy) => {
        expect(policy).toEqual(Matchers.extractPayload(RESPONSE_BODY));
      }));
  });
```

against fixture -
```
{
    name: 'account-holder',
    version: new Date().toISOString(),
    additionalAttributes: { name: 'some other data object' },
  },
```

This fails with 
```
    Failure/Error: expect(response_body).to match_term expected_response_body, diff_options, example
       Actual: {"name":"account-holder","version":"2020-08-17T03:25:28.175Z","additionalAttributes":{"name":"some other data object"}}
       Diff
       --------------------------------------
       Key: - is expected
            + is actual
       Matching keys and values are not shown
        {
       -  "version": "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d{3,}([+-][0-2]\\d(:?[0-5]\\d)?|Z)$"
       +  "version": "2020-08-17T03:25:28.175Z"
        }
       Description of differences
       --------------------------------------
       * Expected "^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d{3,}([+-][0-2]\\d(:?[0-5]\\d)?|Z)$" but got "2020-08-17T03:25:28.175Z" at $.version
```

What makes it work is - Thank you @TimothyJones for the answer. 
```
version: Matchers.term({
    matcher: Matchers.ISO8601_DATETIME_WITH_MILLIS_FORMAT,
    generate: // Some date example
  }),
```

But, using the Matchers.ISO8601_DATETIME_WITH_MILLIS_FORMAT, in such a way wasn't obvious. Maybe the doco could reflect this?

**Comment by mefellows** [comment]
Actually neither of those is the correct way of using the matcher, the correct way is to use the `iso8601DateTimeWithMillis()` matcher function.

The [docs](https://github.com/pact-foundation/pact-js/#matching) are very clear on this:

![Screen Shot 2020-08-31 at 9 34 34 am](https://user-images.githubusercontent.com/53900/91671815-30bee180-eb6d-11ea-8b6a-5be0203ea445.png)

(P.S. thanks for raising, but for Pact JS specific problems please raise them at https://github.com/pact-foundation/pact-js/)

**Comment by TimothyJones** [comment]
@mefellows I don't think the documentation is clear. At least, I can't tell how to use it from that table (every time I need a matcher I end up going and reading the source instead - I've been meaning to address this).

I think there are two improvements we could make here:

* I don't think the helper regex functions should be exposed on the `Matchers` object, as this creates an inconsistent API. This is especially a problem now that JS code autocompletion is better.
* We could improve the documentation of the matchers to make it clear what functions are available and how to use them.

**Comment by TimothyJones** [comment]
Also, I want to transfer this issue to pact-js, but I don't have the option. Possibly it's because I don't have permissions on `pact-specification`. Are you able to do it?
