### ISSUE TITLE
Add examples for text/plain responses

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-specification#8]

**Comment by neilcampbell** [comment]
Added new PR to add these test cases https://github.com/bethesque/pact-specification/pull/20

**Comment by bethesque** [comment]
Cool, they need a content type header.

**Comment by neilcampbell** [comment]
PR updated. Does that also mean we should be adding the application/json header for the rest of the test case?

**Comment by bethesque** [comment]
The rest of which test case?

**Comment by neilcampbell** [comment]
All of the body ones that contain a json response body.

**Comment by bethesque** [comment]
Yes, they probably should.

**Comment by neilcampbell** [comment]
Did you want me to do it as part of this PR #20 or create a new one?

**Comment by bethesque** [comment]
Separate, it's nothing to do with #20.

**Comment by uglyog** [comment]
Closing this, I'm going to add notes on the rules of determining the content type.
